version: "3"
services:
  spark-master:
    image: 3lr1ck/spark-master:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    image: 3lr1ck/spark-worker:latest
    ports:
      - "8081"
    depends_on:
      - spark-master
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

networks:
  spark-network:
