#!/usr/bin/env bash
set -e

DOCKER_TARGET=

case $DOCKER_REPO in
  *master)
    DOCKER_TARGET="master"
    ;;
  *worker)
    DOCKER_TARGET="worker"
    ;;
  *submit)
    DOCKER_TARGET="submit"
    ;;
  *)
    echo "Unknown Docker repo ($DOCKER_REPO), can't tell which target is being build !"
    exit -1
    ;;
esac
echo "Building Spark docker image $IMAGE_NAME using stage $DOCKER_TARGET"
docker build --target $DOCKER_TARGET -t $IMAGE_NAME -f $DOCKERFILE_PATH .
