#!/usr/bin/env bash
set -e

DOCKER_TARGET=
BUILD_ARGS=

case $DOCKER_REPO in
  *master)
    DOCKER_TARGET="master"
    ;;
  *worker)
    DOCKER_TARGET="worker"
    ;;
  *submit)
    DOCKER_TARGET="submit"
    ;;
  *)
    echo "Unknown Docker repo ($DOCKER_REPO), can't tell which target is being build !"
    exit -1
    ;;
esac

if [ "$DOCKER_TAG" = "latest" ]; then
  echo "Building Spark docker image $IMAGE_NAME using stage $DOCKER_TARGET"
else
  SPARK_VERSION=$(echo ${DOCKER_TAG} | sed -r 's/(.+)-hadoop(.+)-jdk8/\1/')
  HADOOP_VERSION=$(echo ${DOCKER_TAG} | sed -r 's/(.+)-hadoop(.+)-jdk8/\2/')
  echo "Building Spark docker image $IMAGE_NAME using stage $DOCKER_TARGET for spark version ${SPARK_VERSION} and hadoop ${HADOOP_VERSION}"
  BUILD_ARGS="${BUILD_ARGS} --build-arg SPARK_VERSION=${SPARK_VERSION} --build-arg HADOOP_VERSION=${HADOOP_VERSION}"
fi
echo "Build arguments: ${BUILD_ARGS}"
docker build ${BUILD_ARGS} --target $DOCKER_TARGET -t $IMAGE_NAME -f $DOCKERFILE_PATH .
