#!/usr/bin/env bash
set -e

DOCKER_TARGET=

case $DOCKER_REPO in
  "spark-master")
    $DOCKER_TARGET="master"
    ;;
  "spark-worker")
    $DOCKER_TARGET="worker"
    ;;
  *)
    echo "Unknown Docker repo (DOCKER_REPO), can't tell which target is being build !"
    exit -1
    ;;
esac

docker build --target $DOCKER_TARGET -t $IMAGE_NAME -f docker/Dockerfile docker
